--== FUNCTIONS ==--

-- CLASSIFICA RAÇA --

CREATE OR REPLACE FUNCTION CLASSIFICA_RACA(val NUMBER)
RETURNS STRING
LANGUAGE SQL
AS
$$
    CASE 
        WHEN val = 1 THEN 'BRANCA' 
        WHEN val = 2 THEN 'PRETA'	
        WHEN val = 3 THEN 'AMARELA'
        WHEN val = 4 THEN 'PARDA'
        WHEN val = 5 THEN 'INDIGENA'
        WHEN val = 9 THEN 'IGNORADO'
        ELSE 'IGNORADO'
    END
$$;

-- CLASSIFICA ESCOLARIDADE

CREATE OR REPLACE FUNCTION CLASSIFICA_ESCOLARIDADE(val NUMBER)
RETURNS STRING
LANGUAGE SQL
AS
$$
    CASE 
        WHEN val = 1 THEN 'Sem instrução' 
        WHEN val = 2 THEN 'Fundamental incompleto'	
        WHEN val = 3 THEN 'Fundamental completa'
        WHEN val = 4 THEN 'Médio incompleto'
        WHEN val = 5 THEN 'Médio completo'
        WHEN val = 6 THEN 'Superior incompleto'
        WHEN val = 7 THEN 'Superior completo'
        WHEN val = 8 THEN 'Pós-graduação, mestrado ou doutorado'   
        ELSE 'IGNORADO'
    END
$$;

-- CLASSIFICA SINTOMA

CREATE OR REPLACE FUNCTION CLASSIFICA_SINTOMA(val NUMBER)
RETURNS STRING
LANGUAGE SQL
AS
$$
    CASE 
        WHEN val = 1 THEN 'Sem instrução' 
        WHEN val = 2 THEN 'Fundamental incompleto'	
        WHEN val = 3 THEN 'Fundamental completa'
        WHEN val = 4 THEN 'Médio incompleto'
        WHEN val = 5 THEN 'Médio completo'
        WHEN val = 6 THEN 'Superior incompleto'
        WHEN val = 7 THEN 'Superior completo'
        WHEN val = 8 THEN 'Pós-graduação, mestrado ou doutorado'   
        ELSE 'IGNORADO'
    END
$$;

--== TABELAS ==--

-- ATENDIMENTO PRIVADO --

CREATE OR REPLACE TABLE DADOS_TRATADOS.ATENDIMENTO_PRIVADO AS (
SELECT 
    CASE 
        WHEN "ATENDIMENTO_PRIVADO?" = 1 THEN 'SIM'
        WHEN "ATENDIMENTO_PRIVADO?" = 2 THEN 'NAO'
        WHEN "ATENDIMENTO_PRIVADO?" = 9 THEN 'IGNORADO'
        WHEN "ATENDIMENTO_PRIVADO?" is null THEN 'NAO_APLICAVEL'
        END AS "ATENDIMENTO_PRIVADO?"
, COUNT(*) * 100.0 / (SELECT COUNT(*) FROM pnad_covid WHERE "PROCUROU_ATENDIMENTO?" = 1) AS Proporcao_Percentual
FROM pnad_covid
WHERE "PROCUROU_ATENDIMENTO?" = 1 
GROUP BY "ATENDIMENTO_PRIVADO?"
)
;

-- ATENDIMENTO SUS --

CREATE OR REPLACE TABLE DADOS_TRATADOS.ATENDIMENTO_SUS AS (
SELECT 
    CASE 
        WHEN "ATENDIMENTO_SUS?" = 1 THEN 'SIM'
        WHEN "ATENDIMENTO_SUS?" = 2 THEN 'NAO'
        WHEN "ATENDIMENTO_SUS?" = 9 THEN 'IGNORADO'
        WHEN "ATENDIMENTO_SUS?" is null THEN 'NAO_APLICAVEL'
        END AS "ATENDIMENTO_SUS?"
, COUNT(*) * 100.0 / (SELECT COUNT(*) FROM pnad_covid WHERE "PROCUROU_ATENDIMENTO?" = 1) AS Proporcao_Percentual
FROM pnad_covid
WHERE "PROCUROU_ATENDIMENTO?" = 1 
GROUP BY "ATENDIMENTO_SUS?"
)
;

-- ATENDIMENTO_SUS_UPA --

CREATE OR REPLACE TABLE DADOS_TRATADOS.ATENDIMENTO_SUS AS (
SELECT 
    CASE 
        WHEN "ATENDIMENTO_DO_SUS/UPA?" = 1 THEN 'SIM'
        WHEN "ATENDIMENTO_DO_SUS/UPA?" = 2 THEN 'NAO'
        WHEN "ATENDIMENTO_DO_SUS/UPA?" = 9 THEN 'IGNORADO'
        WHEN "ATENDIMENTO_DO_SUS/UPA?" is null THEN 'NAO_APLICAVEL'
        END AS "ATENDIMENTO_DO_SUS/UPA?"
, COUNT(*) * 100.0 / (SELECT COUNT(*) FROM pnad_covid WHERE "PROCUROU_ATENDIMENTO?" = 1) AS Proporcao_Percentual
FROM pnad_covid
WHERE "ATENDIMENTO_DO_SUS/UPA?" = 1 
GROUP BY "ATENDIMENTO_DO_SUS/UPA?"
)
;

-- DISTRIBUIÇÃO DE ESCOLARIDADE DOS MORADORES -- 

CREATE OR REPLACE TABLE DISTRIBUICAO_DE_ESCOLARIDADE_DOS_MORADORES AS (
SELECT CLASSIFICA_ESCOLARIDADE(ESCOLARIDADE) AS ESCOLARIDADE,
COUNT(*) * 100.0 / (SELECT COUNT(*) FROM COVID_DATA.BIG_DATA.PNAD_COVID) AS Proporcao_Percentual
FROM COVID_DATA.BIG_DATA.PNAD_COVID
GROUP BY ESCOLARIDADE);

-- DISTRIBUIÇÃO POR IDADE -- 

CREATE OR REPLACE TABLE DISTRIBUICAO_POR_IDADE AS(
SELECT IDADE, COUNT(*) AS Total_Moradores
FROM COVID_DATA.BIG_DATA.PNAD_COVID
GROUP BY IDADE);

-- PROCUROU ATENDIMENTO? -- 

CREATE OR REPLACE TABLE DADOS_TRATADOS.PROCUROU_ATENDIMENTO AS (
SELECT 
    CASE WHEN "PROCUROU_ATENDIMENTO?" = 1 THEN 'SIM'
     WHEN "PROCUROU_ATENDIMENTO?" = 2 THEN 'NAO'
     WHEN "PROCUROU_ATENDIMENTO?" = 9 THEN 'IGNORADO'
     WHEN "PROCUROU_ATENDIMENTO?" IS NULL THEN 'NAO_APLICAVEL'
    END AS "PROCUROU_ATENDIMENTO?",
    COUNT(*) AS Proporcao,
    COUNT(*) * 100.0 / (SELECT COUNT(*) FROM pnad_covid) AS Proporcao_Percentual
FROM PNAD_COVID
GROUP BY "PROCUROU_ATENDIMENTO?");

-- PROPORÇÃO POR RAÇA --

CREATE OR REPLACE TABLE PROPORCAO_POR_RACA AS(
SELECT CLASSIFICA_RACA(RACA) AS "RAÇA",
COUNT(*) * 100.0 / (SELECT COUNT(*) FROM COVID_DATA.BIG_DATA.PNAD_COVID) AS Proporcao_Percentual
FROM COVID_DATA.BIG_DATA.PNAD_COVID
GROUP BY RACA
);

-- REPRESENTATIVIDADE POR SEXO --

WITH FAIXAS_ETARIAS AS (SELECT
  IDADE,
  CASE
    WHEN IDADE BETWEEN 0 AND 12 THEN 'CRIANCA'
    WHEN IDADE BETWEEN 13 AND 17 THEN 'JOVEM'
    WHEN IDADE BETWEEN 18 AND 64 THEN 'ADULTO'
    ELSE 'IDOSO'
  END AS FAIXA_ETARIA,
  "FEBRE_?",
  "TOSSE_?",
  "DOR_DE_GARGANTA_?",
  "DIFICULDADE_RESPIRAR_?",
  DOR_DE_CABECA,
  "DOR_NO_PEITO?",
  "PERDA_DE_CHEIRO_OU_SABOR?"
FROM
  pnad_covid)
SELECT 
    FAIXA_ETARIA,
    CASE 
        WHEN "FEBRE_?" = 1 THEN 'APRESENTOU' 
        WHEN "FEBRE_?" = 2 THEN 'NAO_APRESENTOU'	
        WHEN "FEBRE_?" = 3 THEN 'NAO_SABE'
        ELSE 'IGNORADO'
    END AS "APRESENTOU FEBRE?",
    CASE 
        WHEN "TOSSE_?" = 1 THEN 'APRESENTOU' 
        WHEN "TOSSE_?" = 2 THEN 'NAO_APRESENTOU'	
        WHEN "TOSSE_?" = 3 THEN 'NAO_SABE'
        ELSE 'IGNORADO'
    END AS "APRESENTOU TOSSE?",
    CASE 
        WHEN "DOR_DE_GARGANTA_?" = 1 THEN 'APRESENTOU' 
        WHEN "DOR_DE_GARGANTA_?" = 2 THEN 'NAO_APRESENTOU'	
        WHEN "DOR_DE_GARGANTA_?" = 3 THEN 'NAO_SABE'
        ELSE 'IGNORADO'
    END AS "APRESENTOU DOR DE GARGANTA ?",
    CASE 
        WHEN "DIFICULDADE_RESPIRAR_?" = 1 THEN 'APRESENTOU' 
        WHEN "DIFICULDADE_RESPIRAR_?" = 2 THEN 'NAO_APRESENTOU'	
        WHEN "DIFICULDADE_RESPIRAR_?" = 3 THEN 'NAO_SABE'
        ELSE 'IGNORADO'
    END AS "APRESENTOU DIFICULDADE PARA RESPIRAR ?",
    CASE 
        WHEN DOR_DE_CABECA = 1 THEN 'APRESENTOU' 
        WHEN DOR_DE_CABECA = 2 THEN 'NAO_APRESENTOU' 
        WHEN DOR_DE_CABECA = 3 THEN 'NAO_SABE' 
        ELSE 'IGNORADO'
    END AS "APRESENTOU DOR DE CABECA?",
    CASE 
        WHEN "DOR_NO_PEITO?" = 1 THEN 'APRESENTOU' 
        WHEN "DOR_NO_PEITO?" = 2 THEN 'NAO_APRESENTOU' 
        WHEN "DOR_NO_PEITO?" = 3 THEN 'NAO_SABE' 
        ELSE 'IGNORADO'
    END AS "APRESENTOU DOR NO PEITO?",
    CASE 
        WHEN "PERDA_DE_CHEIRO_OU_SABOR?" = 1 THEN 'APRESENTOU' 
        WHEN "PERDA_DE_CHEIRO_OU_SABOR?" = 2 THEN 'NAO_APRESENTOU' 
        WHEN "PERDA_DE_CHEIRO_OU_SABOR?" = 3 THEN 'NAO_SABE' 
        ELSE 'IGNORADO'
    END AS "APRESENTOU PERDA DE CHEIRO OU SABOR?",
    COUNT(*) AS QTD_TOTAL
FROM FAIXAS_ETARIAS
GROUP BY FAIXA_ETARIA, DOR_DE_CABECA, "FEBRE_?", "TOSSE_?", "DOR_DE_GARGANTA_?", "DIFICULDADE_RESPIRAR_?", "DOR_NO_PEITO?", "PERDA_DE_CHEIRO_OU_SABOR?"
ORDER BY FAIXA_ETARIA
;

-- SINTOMAS POR FAIXA ETARIA --

CREATE OR REPLACE TABLE DADOS_TRATADOS.SINTOMAS_POR_FAIXA_ETARIA AS (
WITH FAIXAS_ETARIAS AS (SELECT
  MES_REFERENCIA,
  IDADE,
  CASE
    WHEN IDADE BETWEEN 0 AND 12 THEN 'CRIANCA'
    WHEN IDADE BETWEEN 13 AND 17 THEN 'JOVEM'
    WHEN IDADE BETWEEN 18 AND 64 THEN 'ADULTO'
    ELSE 'IDOSO'
  END AS FAIXA_ETARIA,
  "FEBRE_?",
  "TOSSE_?",
  "DOR_DE_GARGANTA_?",
  "DIFICULDADE_RESPIRAR_?",
  DOR_DE_CABECA,
  "DOR_NO_PEITO?",
  "PERDA_DE_CHEIRO_OU_SABOR?"
FROM
  COVID_DATA.BIG_DATA.PNAD_COVID)
SELECT 
    MES_REFERENCIA,
    FAIXA_ETARIA,
    CLASSIFICA_SINTOMA("FEBRE_?") AS "APRESENTOU FEBRE?",
    CLASSIFICA_SINTOMA("TOSSE_?") AS "APRESENTOU TOSSE?",
    CLASSIFICA_SINTOMA("DOR_DE_GARGANTA_?") AS "APRESENTOU DOR DE GARGANTA ?",
    CLASSIFICA_SINTOMA("DIFICULDADE_RESPIRAR_?") AS "APRESENTOU DIFICULDADE PARA RESPIRAR ?",
    CLASSIFICA_SINTOMA("DOR_DE_CABECA") AS "APRESENTOU DOR DE CABECA?",
    CLASSIFICA_SINTOMA("DOR_NO_PEITO?") AS "APRESENTOU DOR NO PEITO?",
    CLASSIFICA_SINTOMA("PERDA_DE_CHEIRO_OU_SABOR?") AS "APRESENTOU PERDA DE CHEIRO OU SABOR?",
    COUNT(*) AS QTD_TOTAL,
FROM FAIXAS_ETARIAS
GROUP BY MES_REFERENCIA, FAIXA_ETARIA, DOR_DE_CABECA, "FEBRE_?", "TOSSE_?", "DOR_DE_GARGANTA_?", "DIFICULDADE_RESPIRAR_?", "DOR_NO_PEITO?", "PERDA_DE_CHEIRO_OU_SABOR?"
ORDER BY MES_REFERENCIA, FAIXA_ETARIA, QTD_TOTAL DESC);

-- SINTOMAS POR MES -- 

create or replace table COVID_DATA.DADOS_TRATADOS.SINTOMAS_POR_MES AS (
select  
    mes_referencia,
    classifica_sintoma("FEBRE_?") as "FEBRE_?",
    classifica_sintoma("TOSSE_?") AS "TOSSE_?",
    classifica_sintoma("DOR_DE_GARGANTA_?") AS "DOR_DE_GARGANTA_?",
    classifica_sintoma("DIFICULDADE_RESPIRAR_?") AS "DIFICULDADE_RESPIRAR_?",
    classifica_sintoma("DOR_DE_CABECA") AS "DOR_DE_CABECA",
    classifica_sintoma("DOR_NO_PEITO?") as "DOR_NO_PEITO?",
    classifica_sintoma("PERDA_DE_CHEIRO_OU_SABOR?") as "PERDA_DE_CHEIRO_OU_SABOR?"
from covid_data.big_data.pnad_covid
where 1=1
    and classifica_sintoma("FEBRE_?") = 'APRESENTOU'
    and classifica_sintoma("TOSSE_?") = 'APRESENTOU'
    and classifica_sintoma("DOR_DE_GARGANTA_?") = 'APRESENTOU'
    and classifica_sintoma("DIFICULDADE_RESPIRAR_?") = 'APRESENTOU'
    and classifica_sintoma("DOR_DE_CABECA") = 'APRESENTOU'
    and classifica_sintoma("DOR_NO_PEITO?") = 'APRESENTOU'
    and classifica_sintoma("PERDA_DE_CHEIRO_OU_SABOR?") = 'APRESENTOU');

-- ATENDIMENTO POR MES E UF -- 

create or replace table COVID_DATA.DADOS_TRATADOS.ATENDIMENTO_POR_MES_E_UF AS (
select  
    mes_referencia,
    UF,
    "FOI_PARA_O_POSTO_DE_SAÚDE_?",
    "ATENDIMENTO_DO_SUS/UPA?",
    "ATENDIMENTO_SUS?",
    "ATENDIMENTO_PS_PRIVADO?",
    "ATENDIMENTO_PRIVADO?"
from covid_data.big_data.pnad_covid
where 1=1 
    and "PROCUROU_ATENDIMENTO?" = 1);

-- SUMARIO PERFIL MENSAL -- 

CREATE OR REPLACE TABLE  COVID_DATA.DADOS_TRATADOS.SUMARIO_PERFIL_MENSAL AS  (
SELECT
    UF,
    CASE 
        WHEN CAST(IDADE AS INT) <= 17 THEN '0-17 Anos'
        WHEN CAST(IDADE AS INT) BETWEEN 18 AND 29 THEN '18-29 Anos'
        WHEN CAST(IDADE AS INT) BETWEEN 30 AND 49 THEN '30-49 Anos'
        WHEN CAST(IDADE AS INT) BETWEEN 50 AND 64 THEN '50-64 Anos'
        ELSE '65+ Anos'
    END AS faixa_etaria,
    SEXO,
    RACA,
    ESCOLARIDADE,
    POPULACAO_PROJETADA,
    SUM(CASE WHEN "FEBRE_?" = 1 OR "TOSSE_?" = 1 OR "DIFICULDADE_RESPIRAR_?" = 1 THEN CAST(POPULACAO_PROJETADA AS BIGINT) ELSE 0 END) AS total_sintomaticos,
    SUM(CASE WHEN "FOI_PARA_O_POSTO_DE_SAÚDE_?" = 1 THEN CAST(POPULACAO_PROJETADA AS BIGINT) ELSE 0 END) AS total_procurou_atendimento,
    SUM(CASE WHEN "FICOU_INTERNADO_?" = 1 THEN CAST(POPULACAO_PROJETADA AS BIGINT) ELSE 0 END) AS total_internados,
    SUM(CASE WHEN "FOI_SEDADO_OU_ENTUBADO_?" = '1' THEN CAST(POPULACAO_PROJETADA AS BIGINT) ELSE 0 END) AS total_ventilacao,
    MES_REFERENCIA
FROM
    COVID_DATA.BIG_DATA.PNAD_COVID
GROUP BY
    MES_REFERENCIA,
    UF,
    CASE 
        WHEN CAST(IDADE AS INT) <= 17 THEN '0-17 Anos'
        WHEN CAST(IDADE AS INT) BETWEEN 18 AND 29 THEN '18-29 Anos'
        WHEN CAST(IDADE AS INT) BETWEEN 30 AND 49 THEN '30-49 Anos'
        WHEN CAST(IDADE AS INT) BETWEEN 50 AND 64 THEN '50-64 Anos'
        ELSE '65+ Anos'
    END,
    SEXO,
    RACA,
    ESCOLARIDADE,
    "PLANO_DE_SAUDE_PUBLICO_?",
    POPULACAO_PROJETADA);

-- AUXILIO POR MES

CREATE OR REPLACE TABLE AUXILIO_POR_MES AS (
SELECT
MES_REFERENCIA,
    CASE WHEN "RECEBEU_AUXILIO_EMERGENCIAL_DO_GOVERNO?" = 1 THEN 'SIM'
    WHEN "RECEBEU_AUXILIO_EMERGENCIAL_DO_GOVERNO?" = 2 THEN 'NAO'
    END AS "RECEBEU_AUXILIO_EMERGENCIAL_DO_GOVERNO?"
FROM COVID_DATA.BIG_DATA.PNAD_COVID);

-- RENDA PROJETADA POR ESCOLARIDADE

CREATE OR REPLACE TABLE RENDA_PROJETADA_POR_ESCOLARIDADE AS (
SELECT
    CASE ESCOLARIDADE
        WHEN 1 THEN 'Sem instrução'
        WHEN 2 THEN 'Fundamental incompleto ou equivalente'
        WHEN 3 THEN 'Fundamental completo ou equivalente'
        WHEN 4 THEN 'Médio incompleto ou equivalente'
        WHEN 5 THEN 'Médio completo ou equivalente'
        WHEN 6 THEN 'Superior incompleto ou equivalente'
        WHEN 7 THEN 'Superior completo ou equivalente'
        WHEN 8 THEN 'Pós-graduação ou mais'
        ELSE 'Não informado'
    END AS ESCOLARIDADE,
    SUM(C01012 * POPULACAO_PROJETADA) / SUM(POPULACAO_PROJETADA) AS Renda_Media_Ponderada
FROM
    COVID_DATA.BIG_DATA.PNAD_COVID
WHERE
    C01012 IS NOT NULL AND POPULACAO_PROJETADA IS NOT NULL AND ESCOLARIDADE IS NOT NULL
GROUP BY
    ESCOLARIDADE
ORDER BY
    ESCOLARIDADE);